### PR TITLE
Fix css, route and totp flag

### LINKED ISSUE #97: TOTP does not follow login style

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #97

### CODE REVIEW

File: appinfo/routes.php [hunk 1]
```diff
@@ -13,7 +13,7 @@
         ['name' => 'admin_settings#set', 'url' => '/settings/admin/set', 'verb' => 'POST'],
         ['name' => 'admin_settings#getCustomization', 'url' => '/settings/admin/getCustomization/{providername}', 'verb' => 'GET'],
         ['name' => 'personal_settings#set', 'url' => '/settings/personal/set', 'verb' => 'POST'],
-        ['name' => 'css#login', 'url' => '/api/login', 'verb' => 'GET'],
-        ['name' => 'css#dashboard', 'url' => '/api/dashboard', 'verb' => 'GET']
+        ['name' => 'css#login', 'url' => '/api/login.css', 'verb' => 'GET'],
```
Comment (skjnldsv) [inline appinfo/routes.php:16]: Helps in the network logging

File: css/login_static.css [hunk 2]
```diff
@@ -28,6 +28,13 @@ background-color : rgba(0, 0, 0, .5) !important;
 }
 
 /* Load more fitting image sizes based on screen resolution */
+
+@media only screen and (max-width: 1920px) {
+	body#body-login {
+		background-image: url('https://source.unsplash.com/featured/1920x1080?nature,nature') !important;
+	}
+}
```
Comment (skjnldsv) [inline css/login_static.css:36]: Missing small section

**Comment by newhinton** [comment]
Ohhh there is a `@NoTwoFactorRequired`-flag! I did not know that, thank you!

It seems that this pr fully fixes the issue, thanks!
